version: "3.8"

services:

  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - $HOME/boilerplate/postgres:/var/lib/postgresql/data
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:v1
    container_name: api
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: bridge
    